name: linting-python-code

on: push

jobs: 
   lint:
    name: Run Super-Linter
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Super-Linter
        uses: super-linter/super-linter@v7.2.1
