name: linting-python-code

on: push

jobs: 
   lint:
    name: Run Super-Linter
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Super-Linter
        uses: super-linter/super-linter@v7.2.1
        env:
          VALIDATE_ALL_CODEBASE: true
          GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
          VALIDATE_YAML: true
          VALIDATE_JSON: true
          VALIDATE_PYTHON: true
          VALIDATE_JAVASCRIPT_ES: true
          VALIDATE_CHECKOV: false  # Ensure Checkov runs correctly
          VALIDATE_GITHUB_ACTIONS: false  # Validate GitHub Actions YAML files
